create extension if not exists pgcrypto;

create table if not exists public.portfolio_profile (
  id bigint primary key default 1,
  user_id uuid not null default auth.uid(),
  brand_name text not null default '',
  full_name text not null default '',
  years_worked integer not null default 0,
  software_role text not null default '',
  software_headline text not null default '',
  software_intro text not null default '',
  software_about_title text not null default '',
  software_about_body text not null default '',
  software_photo_url text not null default '',
  software_version text not null default '',
  contact_email text not null default '',
  contact_title text not null default '',
  contact_description text not null default '',
  contact_location_label text not null default '',
  contact_availability text not null default '',
  contact_linkedin_url text not null default '',
  contact_github_url text not null default '',
  contact_resume_url text not null default '',
  civil_role text not null default '',
  civil_headline text not null default '',
  civil_intro text not null default '',
  civil_philosophy text not null default '',
  civil_focus text not null default '',
  civil_certification text not null default '',
  civil_certification_note text not null default '',
  civil_base text not null default '',
  civil_specialty text not null default '',
  civil_photo_url text not null default '',
  updated_at timestamptz not null default now()
);

alter table public.portfolio_profile add column if not exists brand_name text not null default '';
alter table public.portfolio_profile add column if not exists software_role text not null default '';
alter table public.portfolio_profile add column if not exists software_headline text not null default '';
alter table public.portfolio_profile add column if not exists software_intro text not null default '';
alter table public.portfolio_profile add column if not exists software_about_title text not null default '';
alter table public.portfolio_profile add column if not exists software_about_body text not null default '';
alter table public.portfolio_profile add column if not exists software_photo_url text not null default '';
alter table public.portfolio_profile add column if not exists software_version text not null default '';
alter table public.portfolio_profile add column if not exists contact_email text not null default '';
alter table public.portfolio_profile add column if not exists contact_title text not null default '';
alter table public.portfolio_profile add column if not exists contact_description text not null default '';
alter table public.portfolio_profile add column if not exists contact_location_label text not null default '';
alter table public.portfolio_profile add column if not exists contact_availability text not null default '';
alter table public.portfolio_profile add column if not exists contact_linkedin_url text not null default '';
alter table public.portfolio_profile add column if not exists contact_github_url text not null default '';
alter table public.portfolio_profile add column if not exists contact_resume_url text not null default '';
alter table public.portfolio_profile add column if not exists civil_role text not null default '';
alter table public.portfolio_profile add column if not exists civil_headline text not null default '';
alter table public.portfolio_profile add column if not exists civil_intro text not null default '';
alter table public.portfolio_profile add column if not exists civil_philosophy text not null default '';
alter table public.portfolio_profile add column if not exists civil_focus text not null default '';
alter table public.portfolio_profile add column if not exists civil_certification text not null default '';
alter table public.portfolio_profile add column if not exists civil_certification_note text not null default '';
alter table public.portfolio_profile add column if not exists civil_base text not null default '';
alter table public.portfolio_profile add column if not exists civil_specialty text not null default '';
alter table public.portfolio_profile add column if not exists civil_photo_url text not null default '';

create table if not exists public.portfolio_skills (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid(),
  sort_order integer not null default 0,
  category text not null default '',
  name text not null default '',
  level text not null default '',
  description text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.portfolio_experiences (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid(),
  sort_order integer not null default 0,
  company text not null default '',
  role text not null default '',
  period text not null default '',
  location text not null default '',
  description text not null default '',
  achievements text not null default '',
  stack text not null default '',
  updated_at timestamptz not null default now()
);

alter table public.portfolio_experiences add column if not exists achievements text not null default '';
alter table public.portfolio_experiences add column if not exists location text not null default '';
alter table public.portfolio_experiences add column if not exists stack text not null default '';

create table if not exists public.portfolio_repos (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid(),
  sort_order integer not null default 0,
  name text not null default '',
  url text not null default '',
  description text not null default '',
  stack text not null default '',
  badge text not null default '',
  metrics text not null default '',
  updated_at timestamptz not null default now()
);

alter table public.portfolio_repos add column if not exists stack text not null default '';
alter table public.portfolio_repos add column if not exists badge text not null default '';
alter table public.portfolio_repos add column if not exists metrics text not null default '';

create table if not exists public.portfolio_civil_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid(),
  sort_order integer not null default 0,
  section_key text not null default 'projects',
  title text not null default '',
  subtitle text not null default '',
  period text not null default '',
  description text not null default '',
  link text not null default '',
  stack text not null default '',
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists portfolio_profile_updated_at on public.portfolio_profile;
create trigger portfolio_profile_updated_at
before update on public.portfolio_profile
for each row execute function public.set_updated_at();

drop trigger if exists portfolio_experiences_updated_at on public.portfolio_experiences;
create trigger portfolio_experiences_updated_at
before update on public.portfolio_experiences
for each row execute function public.set_updated_at();

drop trigger if exists portfolio_skills_updated_at on public.portfolio_skills;
create trigger portfolio_skills_updated_at
before update on public.portfolio_skills
for each row execute function public.set_updated_at();

drop trigger if exists portfolio_repos_updated_at on public.portfolio_repos;
create trigger portfolio_repos_updated_at
before update on public.portfolio_repos
for each row execute function public.set_updated_at();

drop trigger if exists portfolio_civil_items_updated_at on public.portfolio_civil_items;
create trigger portfolio_civil_items_updated_at
before update on public.portfolio_civil_items
for each row execute function public.set_updated_at();

alter table public.portfolio_profile enable row level security;
alter table public.portfolio_skills enable row level security;
alter table public.portfolio_experiences enable row level security;
alter table public.portfolio_repos enable row level security;
alter table public.portfolio_civil_items enable row level security;

drop policy if exists "Public read profile" on public.portfolio_profile;
create policy "Public read profile"
  on public.portfolio_profile
  for select
  using (true);

drop policy if exists "Public read experiences" on public.portfolio_experiences;
create policy "Public read experiences"
  on public.portfolio_experiences
  for select
  using (true);

drop policy if exists "Public read skills" on public.portfolio_skills;
create policy "Public read skills"
  on public.portfolio_skills
  for select
  using (true);

drop policy if exists "Public read repos" on public.portfolio_repos;
create policy "Public read repos"
  on public.portfolio_repos
  for select
  using (true);

drop policy if exists "Public read civil items" on public.portfolio_civil_items;
create policy "Public read civil items"
  on public.portfolio_civil_items
  for select
  using (true);

drop policy if exists "Admin write profile" on public.portfolio_profile;
create policy "Admin write profile"
  on public.portfolio_profile
  for all
  to authenticated
  using (auth.jwt() ->> 'email' = 'diieego.brz@gmail.com')
  with check (auth.jwt() ->> 'email' = 'diieego.brz@gmail.com');

drop policy if exists "Admin write experiences" on public.portfolio_experiences;
create policy "Admin write experiences"
  on public.portfolio_experiences
  for all
  to authenticated
  using (auth.jwt() ->> 'email' = 'diieego.brz@gmail.com')
  with check (auth.jwt() ->> 'email' = 'diieego.brz@gmail.com');

drop policy if exists "Admin write skills" on public.portfolio_skills;
create policy "Admin write skills"
  on public.portfolio_skills
  for all
  to authenticated
  using (auth.jwt() ->> 'email' = 'diieego.brz@gmail.com')
  with check (auth.jwt() ->> 'email' = 'diieego.brz@gmail.com');

drop policy if exists "Admin write repos" on public.portfolio_repos;
create policy "Admin write repos"
  on public.portfolio_repos
  for all
  to authenticated
  using (auth.jwt() ->> 'email' = 'diieego.brz@gmail.com')
  with check (auth.jwt() ->> 'email' = 'diieego.brz@gmail.com');

drop policy if exists "Admin write civil items" on public.portfolio_civil_items;
create policy "Admin write civil items"
  on public.portfolio_civil_items
  for all
  to authenticated
  using (auth.jwt() ->> 'email' = 'diieego.brz@gmail.com')
  with check (auth.jwt() ->> 'email' = 'diieego.brz@gmail.com');
